### ISSUE TITLE
Sorry, unrelated to this repo!

### ISSUE THREAD

**Issue by jdemonasterio** [alfredormz/pg-schema-migration#1]
Repeat of: https://github.com/BrunoSalerno/citylines/issues/129

Hi @alfredormz  and sorry for bothering  :)

I was wondering if there is a way to msg devs working @properati about the broken BigQuery link (https://www.properati.com.ar/data). 
Did this go private or was it moved somewhere else? Is this option still available/live?

I know I can just use the posted .csv.gz links but it would be much easier to iterate properati data  analysis with any link to data in bigQuery. It would be awesomeif this was the case as I intend to use Google's collab notebooks and not have to worry about data upload/download to/from the notebook. 

Ty!

I'll close this immediately.

**Comment by alfredormz** [comment]
@jdemonasterio hi, you can reach Martin Sarsale at martin@properati.com
